required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for deepcopy generation
    "k8s.io/code-generator/cmd/openapi-gen", # for openapi generation
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
    "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
    "github.com/golang/protobuf/protoc-gen-go",
    ]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-03-20
  revision = "8d4083db9aa0d2fae6588c1acdbe6a1f5db461e3"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[[constraint]]
  name = "golang.org/x/net"
  revision="640f4622ab692b87c2f3a94265e6f579fe38263d"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.9"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.13.3"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[[constraint]]
  name = "github.com/kubeflow/tf-operator"
  branch = "v0.7-branch"

[[constraint]]
  name = "github.com/kubeflow/pytorch-operator"
  branch = "v0.7-branch"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  branch = "master"

[[constraint]]
  name = "github.com/c-bata/goptuna"
  version = "v0.5.1"

[[prune.project]]
  name = "github.com/kubeflow/katib"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/gengo"
  unused-packages = false

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.2.0"
